# Generated by Django 5.2.8 on 2025-12-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titulo")),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualizacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagina",
                "verbose_name_plural": "Paginas",
                "ordering": ["title"],
            },
        ),
    ]
