# Generated by Django 5.2.8 on 2026-01-02 00:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_pages_options_pages_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pages",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="Contenido"),
        ),
    ]
