# Generated by Django 5.2.8 on 2025-11-26 03:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Servicio", "verbose_name_plural": "Servicios"},
        ),
    ]
