# Generated by Django 5.2.8 on 2025-11-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_service_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["-created"],
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
            },
        ),
        migrations.AlterField(
            model_name="service",
            name="created",
            field=models.DateField(auto_now_add=True, verbose_name="Fecha de creacion"),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualizacion"
            ),
        ),
    ]
