# Generated by Django 5.2.8 on 2025-11-29 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 29, 14, 6, 24, 545847, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Fecha de publicacion",
            ),
        ),
    ]
