# Generated by Django 5.2.8 on 2025-11-29 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_post_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de publicacion"
            ),
        ),
    ]
