# Generated by Django 5.2.8 on 2025-11-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_post_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                related_name="posts", to="blog.category", verbose_name="Categorias"
            ),
        ),
    ]
