# Generated by Django 5.2.8 on 2025-12-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Socialnetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Nombre clave"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Red social")),
                ("url", models.URLField(blank=True, null=True, verbose_name="Enlace")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualizacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Enlace",
                "verbose_name_plural": "Enlaces",
                "ordering": ["name"],
            },
        ),
    ]
