# Generated by Django 5.2.8 on 2025-12-28 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Socialnetwork",
            new_name="Links",
        ),
    ]
